### PR TITLE
add mediumpost url to readme

### PR DESCRIPTION
**Pull request by fcakyon**

### CODE REVIEW

**Comment by ivanpanshin** [comment]
Thanks for pointing that out!

**Comment by fcakyon** [comment]
It was very hard to find the medium post from your repo, thought others should easily find :)

Amazing tutorial and template project btw, thanks for publishing. Do you have any plans on adding a task queue via celery/redis to dockerized flask app? Maybe in a different repo, or into this project

**Comment by ivanpanshin** [comment]
Great question. In fact, yes, I have such plans. I will publish more articles with code on GitHub that focus on deploying models. For instance, techniques for making models smaller, converting them to other formats, etc. But also, yeah, I will definitely dig deeper into stuff like celery/redis. 

But for the next couple of weeks I'm planning to focus on my new article about semantic segmentation for pneumothorax based on this competition: https://www.kaggle.com/c/siim-acr-pneumothorax-segmentation

**Comment by fcakyon** [comment]
thanks again for the fast response, will be following you for your future articles, pneumothorax segmentation also seems to be interesting

**Pull request merged**
